export enum PublishingStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum ImportStatus {
  SCRAPED = 'SCRAPED',
  VALIDATED = 'VALIDATED',
  IMPORTED = 'IMPORTED',
  REJECTED = 'REJECTED',
}

export enum AuthorRole {
  AUTHOR = 'AUTHOR',
  CO_AUTHOR = 'CO_AUTHOR',
  EDITOR = 'EDITOR',
  TRANSLATOR = 'TRANSLATOR',
  ILLUSTRATOR = 'ILLUSTRATOR',
}

export enum MediaRole {
  COVER_FRONT = 'COVER_FRONT',
  COVER_BACK = 'COVER_BACK',
  SPINE = 'SPINE',
  INSIDE = 'INSIDE',
  PREVIEW = 'PREVIEW',
  THUMBNAIL = 'THUMBNAIL',
  BANNER = 'BANNER',
}

export enum InventoryTransactionType {
  OPENING = 'OPENING',
  RECEIVE = 'RECEIVE',
  RESERVE = 'RESERVE',
  RESERVATION_RELEASE = 'RESERVATION_RELEASE',
  SALE = 'SALE',
  RETURN = 'RETURN',
  DAMAGE = 'DAMAGE',
  ADJUSTMENT_IN = 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT = 'ADJUSTMENT_OUT',
}
